// clean-architecture-for-frontends/frontend/02-create-components/react-project/src/components/TodoInput/TodoInput.tsx
import { useState } from "react";

type Props = {
  onSubmit: (task: string) => void;
};

function TodoInput(props: Props) {
  const { onSubmit } = props;

  const [task, setTask] = useState<string>("");

  function handleChange(event: React.ChangeEvent<HTMLInputElement>) {
    const task = event.target.value;

    setTask(task);
  }

  function handleSubmit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();

    const taskValue = task?.trim();

    if (!taskValue.length) {
      return;
    }

    onSubmit(taskValue);
    setTask("");
  }

  return (
    <form onSubmit={handleSubmit}>
      <input
        type="text"
        placeholder="Type your task..."
        value={task}
        onChange={handleChange}
      />
    </form>
  );
}

export default TodoInput;

// clean-architecture-for-frontends/frontend/05-multiple-apps/vue-project/src/components/TodoInput/TodoInput.vue
<script setup lang="ts">
import { ref } from "vue";

const { onSubmit } = defineProps<{
  onSubmit: (task: string) => void;
}>();

const task = ref<string>("");

function handleSubmit() {
  const taskValue = task.value?.trim();

  if (!taskValue.length) {
    return;
  }

  onSubmit(taskValue);
  task.value = "";
}
</script>

<template>
  <form @submit.prevent="handleSubmit">
    <input v-model="task" type="text" placeholder="Type your task..." />
  </form>
</template>
