// clean-architecture-for-frontends/frontend/05-multiple-apps/react-project/src/components/TodoList/TodoList.tsx
import { useEffect, useMemo, useState } from "react";
import { TaskProps, TodoListItem } from "../TodoListItem";
import { TodoInput } from "../TodoInput";
import { TodoList as TodoListClass } from "../../entities";
import { TodosGateway } from "../../gateways";

type Props = {
  todosGateway: TodosGateway;
};

function TodoList(props: Props) {
  const { todosGateway } = props;

  const [tasks, setTasks] = useState<TaskProps[]>([]);
  const todoList = useMemo(() => {
    return new TodoListClass();
  }, []);

  const totalTasks = todoList.getTotal();
  const hasValidTasks = totalTasks > 0;

  function handleSubmit(task: string) {
    const newTask = todoList.add(task);
    setTasks((prevState) => [...prevState, newTask]);
  }

  function handleToggleDone(taskId: string) {
    const updatedTasks = todoList.toggleDone(taskId);
    setTasks(updatedTasks);
  }

  function handleRemoveTask(taskId: string) {
    const updatedTasks = todoList.remove(taskId);
    setTasks(updatedTasks);
  }

  useEffect(() => {
    async function fetchTodos() {
      try {
        const res = await todosGateway.getTodos();
        const tasks = res.map((task) => todoList.add(task.text));

        setTasks(tasks);
      } catch (error) {
        alert("An error has occurred");
      }
    }

    fetchTodos();
  }, [todoList, todosGateway]);

  return (
    <div>
      <h1>React - TODO List</h1>

      <p>
        Total items: <span data-testid="total-tasks">{totalTasks}</span>
      </p>

      <TodoInput onSubmit={handleSubmit} />

      {hasValidTasks && (
        <ul>
          {tasks.map((task) => (
            <TodoListItem
              key={task.id}
              task={task}
              onToggleDone={handleToggleDone}
              onRemoveTask={handleRemoveTask}
            />
          ))}
        </ul>
      )}
    </div>
  );
}

export default TodoList;

// clean-architecture-for-frontends/frontend/05-multiple-apps/vue-project/src/components/TodoList/TodoList.vue
<script setup lang="ts">
import { computed, inject, onMounted, ref } from "vue";
import { TodoInput } from "../TodoInput";
import { TodoListItem } from "../TodoListItem";
import { TodoList } from "../../entities";
import { TodosGateway } from "../../gateways";

const todoList = ref(new TodoList());
const hasValidTasks = computed(() => todoList.value.getTotal() > 0);

function handleSubmit(task: string) {
  todoList.value.add(task);
}

function handleToggleDone(taskId: string) {
  todoList.value.toggleDone(taskId);
}

function handleRemoveTask(taskId: string) {
  todoList.value.remove(taskId);
}

onMounted(() => {
  async function fetchTodos() {
    try {
      const todosGateway = inject<TodosGateway>("todosGateway");
      const tasks = await todosGateway?.getTodos();

      tasks?.forEach((task) => todoList.value.add(task.text));
    } catch (error) {
      alert("An error has occurred");
    }
  }

  fetchTodos();
});
</script>

<template>
  <div>
    <h1>Vue - TODO List</h1>

    <p>
      Total items:
      <span data-testid="total-tasks">{{ todoList.getTotal() }}</span>
    </p>

    <TodoInput :onSubmit="handleSubmit" />

    <ul v-if="hasValidTasks">
      <TodoListItem
        v-for="task in todoList.getTasks()"
        :key="task.id"
        :task="task"
        :onToggleDone="handleToggleDone"
        :onRemoveTask="handleRemoveTask"
      />
    </ul>
  </div>
</template>
