// clean-architecture-for-frontends/frontend/02-create-components/react-project/src/components/TodoList/TodoList.tsx
import axios from "axios";
import { useEffect, useState } from "react";
import { v4 as uuidv4 } from "uuid";
import { TaskProps, TodoListItem } from "../TodoListItem";
import { TodoInput } from "../TodoInput";

function TodoList() {
  const [tasks, setTasks] = useState<TaskProps[]>([]);

  const totalTasks = tasks.length;
  const hasValidTasks = tasks.length > 0;

  function handleSubmit(task: string) {
    const newTask = {
      id: uuidv4(),
      text: task,
      isCompleted: false,
    };

    setTasks((prevState) => [...prevState, newTask]);
  }

  function handleToggleDone(taskId: string) {
    const updatedTasks = tasks.map((task) => {
      if (task.id === taskId) {
        return {
          ...task,
          isCompleted: !task.isCompleted,
        };
      }

      return task;
    });

    setTasks(updatedTasks);
  }

  function handleRemoveTask(taskId: string) {
    const updatedTasks = tasks.filter((task) => task.id !== taskId);

    setTasks(updatedTasks);
  }

  useEffect(() => {
    async function fetchTodos() {
      try {
        const res = await axios.get("http://localhost:3000/todos");
        const tasks = res.data;

        setTasks(tasks);
      } catch (error) {
        alert("An error has occurred");
      }
    }

    fetchTodos();
  }, []);

  return (
    <div>
      <h1>React - TODO List</h1>

      <p>
        Total items: <span data-testid="total-tasks">{totalTasks}</span>
      </p>

      <TodoInput onSubmit={handleSubmit} />

      {hasValidTasks && (
        <ul>
          {tasks.map((task) => (
            <TodoListItem
              key={task.id}
              task={task}
              onToggleDone={handleToggleDone}
              onRemoveTask={handleRemoveTask}
            />
          ))}
        </ul>
      )}
    </div>
  );
}

export default TodoList;

// clean-architecture-for-frontends/frontend/05-multiple-apps/vue-project/src/components/TodoList/TodoList.vue
<script setup lang="ts">
import { computed, inject, onMounted, ref } from "vue";
import { TodoInput } from "../TodoInput";
import { TodoListItem } from "../TodoListItem";
import { TodoList } from "../../entities";
import { TodosGateway } from "../../gateways";

const todoList = ref(new TodoList());
const hasValidTasks = computed(() => todoList.value.getTotal() > 0);

function handleSubmit(task: string) {
  todoList.value.add(task);
}

function handleToggleDone(taskId: string) {
  todoList.value.toggleDone(taskId);
}

function handleRemoveTask(taskId: string) {
  todoList.value.remove(taskId);
}

onMounted(() => {
  async function fetchTodos() {
    try {
      const todosGateway = inject<TodosGateway>("todosGateway");
      const tasks = await todosGateway?.getTodos();

      tasks?.forEach((task) => todoList.value.add(task.text));
    } catch (error) {
      alert("An error has occurred");
    }
  }

  fetchTodos();
});
</script>

<template>
  <div>
    <h1>Vue - TODO List</h1>

    <p>
      Total items:
      <span data-testid="total-tasks">{{ todoList.getTotal() }}</span>
    </p>

    <TodoInput :onSubmit="handleSubmit" />

    <ul v-if="hasValidTasks">
      <TodoListItem
        v-for="task in todoList.getTasks()"
        :key="task.id"
        :task="task"
        :onToggleDone="handleToggleDone"
        :onRemoveTask="handleRemoveTask"
      />
    </ul>
  </div>
</template>
