// clean-architecture-for-frontends/frontend/05-multiple-apps/vue-project/src/components/TodoListItem/TodoListItem.vue
<script setup lang="ts">
import { Task } from "../../entities";

defineProps<{
  task: Task;
  onToggleDone: (taskId: string) => void;
  onRemoveTask: (taskId: string) => void;
}>();
</script>

<template>
  <li>
    <input
      :checked="task.isCompleted"
      type="checkbox"
      @change="onToggleDone(task.id)"
    />
    <span :class="{ 'task-completed': task.isCompleted }">{{ task.text }}</span>
    <button type="button" @click="onRemoveTask(task.id)">Remove</button>
  </li>
</template>

<style scoped>
.task-completed {
  text-decoration: line-through;
}
</style>

// clean-architecture-for-frontends/frontend/02-create-components/react-project/src/components/TodoListItem/TodoListItem.tsx
export type TaskProps = {
  id: string;
  text: string;
  isCompleted: boolean;
};

type Props = {
  task: TaskProps;
  onToggleDone: (taskId: string) => void;
  onRemoveTask: (taskId: string) => void;
};

function TodoListItem(props: Props) {
  const { task, onToggleDone, onRemoveTask } = props;

  return (
    <li>
      <input
        type="checkbox"
        checked={task.isCompleted}
        onChange={() => onToggleDone(task.id)}
      />

      <span
        style={{
          textDecoration: task.isCompleted ? "line-through" : "none",
        }}
      >
        {task.text}
      </span>

      <button type="button" onClick={() => onRemoveTask(task.id)}>
        Remove
      </button>
    </li>
  );
}

export default TodoListItem;
